name: Create Release

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest Git tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "VERSION=${TAG}" >> $GITHUB_ENV

      - name: Get current date
        id: get_date
        run: |
          DATE=$(date +"%B, %d, %Y")
          echo "DATE=${DATE}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }} (${{ env.DATE }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
